<a href="https://colab.research.google.com/github/Manuj99/pytorch/blob/pytorch_1/pytorch_fundamentals_excercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
rand_tensor_1 = torch.rand(7,7)
rand_tensor_1

tensor([[0.9980, 0.9031, 0.5597, 0.5014, 0.4472, 0.3358, 0.4122],
        [0.5488, 0.9929, 0.6936, 0.9345, 0.3986, 0.1067, 0.0212],
        [0.1545, 0.4608, 0.3073, 0.8483, 0.2068, 0.4290, 0.4190],
        [0.8414, 0.4744, 0.0642, 0.3477, 0.2141, 0.6164, 0.2711],
        [0.2288, 0.6335, 0.9255, 0.2034, 0.5957, 0.1127, 0.6130],
        [0.4292, 0.4127, 0.2343, 0.2430, 0.4055, 0.4609, 0.0858],
        [0.8329, 0.5533, 0.8112, 0.6487, 0.7823, 0.3375, 0.3868]])

In [3]:
rand_tensor_2 = torch.rand(1,7)
rand_tensor_2

tensor([[0.0103, 0.6651, 0.8837, 0.8421, 0.8721, 0.8648, 0.9551]])

In [4]:
rand_res = rand_tensor_1 @ rand_tensor_2.T
rand_res

tensor([[2.6017],
        [2.5260],
        [2.2455],
        [1.6525],
        [2.6152],
        [1.5246],
        [2.9832]])

In [11]:
!nvidia-smi

Mon Sep 29 23:03:55 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   41C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [12]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [13]:
torch.cuda.device_count()

1

In [23]:
torch.cuda.manual_seed(1234)

In [35]:
# torch.manual_seed(0)
# torch.cuda.seed()
torch.cuda.manual_seed(1234)
rand_tensor_seed1 = torch.rand(7,7, device=device)
# rand_tensor_seed1.to(device)
print(rand_tensor_seed1)
# torch.manual_seed(0)
# torch.cuda.seed()
torch.cuda.manual_seed(1234)
rand_tensor_seed2 = torch.rand(1,7, device=device)
# rand_tensor_seed2.to(device)
print(rand_tensor_seed2)
rand_res_seed = torch.mm(rand_tensor_seed1, rand_tensor_seed2.T)
print(rand_res_seed)

tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903],
        [0.3394, 0.5451, 0.7312, 0.3864, 0.5959, 0.7578, 0.2126],
        [0.7198, 0.9845, 0.5518, 0.0981, 0.0582, 0.5839, 0.1083],
        [0.9461, 0.3170, 0.8328, 0.6676, 0.2886, 0.9022, 0.8115],
        [0.1784, 0.9534, 0.1486, 0.3882, 0.7977, 0.1752, 0.5777],
        [0.1949, 0.8499, 0.3125, 0.2156, 0.0383, 0.4934, 0.3138],
        [0.3121, 0.5664, 0.1266, 0.7097, 0.0040, 0.5147, 0.2811]],
       device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903]],
       device='cuda:0')
tensor([[2.5893],
        [2.1242],
        [1.8872],
        [2.5468],
        [1.7516],
        [1.6445],
        [1.6517]], device='cuda:0')


In [42]:
torch.manual_seed(1234)
rand_tensor_3 = torch.rand(2,3).to(device)
torch.manual_seed(1234)
rand_tensor_4 = torch.rand(2,3).to(device)
rand_res_2 = rand_tensor_3@rand_tensor_4.T
rand_res_2

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [49]:
print(rand_res_2.min())
print(torch.min(rand_res_2))
print(rand_res_2.argmin())
print(torch.argmin(rand_res_2))

tensor(0.2161, device='cuda:0')
tensor(0.2161, device='cuda:0')
tensor(1, device='cuda:0')
tensor(1, device='cuda:0')


In [51]:
print(rand_res_2.max())
print(torch.max(rand_res_2))
print(rand_res_2.argmax())
print(torch.argmax(rand_res_2))

tensor(0.6287, device='cuda:0')
tensor(0.6287, device='cuda:0')
tensor(3, device='cuda:0')
tensor(3, device='cuda:0')


In [52]:
torch.manual_seed(7)
# torch.cuda.manual_seed(7)
rand_tensor_5 = torch.rand(1,1,1,10)
print(rand_tensor_5)
print(rand_tensor_5.shape)
rand_tensor_5_squeezed = rand_tensor_5.squeeze()
print(rand_tensor_5_squeezed)
print(rand_tensor_5_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
