<a href="https://colab.research.google.com/github/Manuj99/pytorch/blob/pytorch_1/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


In [4]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
scaler.item()

7

In [7]:
vector = torch.tensor([1,4])
vector

tensor([1, 4])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
matrix = torch.tensor([[1,4], [2,5]])
matrix

tensor([[1, 4],
        [2, 5]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
matrix[1]

tensor([2, 5])

In [14]:
tensor = torch.tensor([[[1,2,3],[4,5,6]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 2, 3])

In [17]:
tensor[0][1][2].item()

6

In [18]:
# Creating Random Tensors of size (3, 4)
random_tensor = torch.rand(3,3,5)
random_tensor


tensor([[[0.8090, 0.3824, 0.8276, 0.7001, 0.8252],
         [0.8029, 0.3393, 0.0793, 0.7262, 0.2023],
         [0.5474, 0.6114, 0.5298, 0.4988, 0.7395]],

        [[0.1619, 0.8034, 0.7555, 0.5781, 0.6464],
         [0.9653, 0.8444, 0.1594, 0.2712, 0.5659],
         [0.1655, 0.0408, 0.3639, 0.5105, 0.9733]],

        [[0.4396, 0.0046, 0.3969, 0.7408, 0.6744],
         [0.0266, 0.1445, 0.7428, 0.3780, 0.5255],
         [0.1635, 0.9301, 0.3990, 0.1812, 0.7813]]])

In [19]:
random_image_size_tensor = torch.rand(3,224,224)

In [20]:
random_image_size_tensor

tensor([[[0.0307, 0.3622, 0.5754,  ..., 0.3622, 0.3515, 0.3574],
         [0.3018, 0.4151, 0.9478,  ..., 0.7618, 0.6407, 0.5385],
         [0.7265, 0.7587, 0.3878,  ..., 0.6597, 0.1604, 0.5351],
         ...,
         [0.2185, 0.9631, 0.0639,  ..., 0.7043, 0.5222, 0.5329],
         [0.9005, 0.5145, 0.5604,  ..., 0.7101, 0.5763, 0.9740],
         [0.7618, 0.6759, 0.1679,  ..., 0.8919, 0.6985, 0.8160]],

        [[0.0494, 0.0476, 0.8848,  ..., 0.2275, 0.5557, 0.9704],
         [0.5526, 0.8303, 0.3031,  ..., 0.2025, 0.3873, 0.6596],
         [0.5956, 0.6995, 0.2246,  ..., 0.4769, 0.1905, 0.7405],
         ...,
         [0.9867, 0.6099, 0.2953,  ..., 0.1296, 0.3308, 0.5436],
         [0.5820, 0.8755, 0.9290,  ..., 0.4271, 0.1841, 0.2996],
         [0.6206, 0.0473, 0.9402,  ..., 0.5364, 0.2903, 0.2772]],

        [[0.2179, 0.9885, 0.3659,  ..., 0.6469, 0.3477, 0.1618],
         [0.1800, 0.0201, 0.7522,  ..., 0.1955, 0.4047, 0.6697],
         [0.2911, 0.1458, 0.7522,  ..., 0.3424, 0.2726, 0.

In [21]:
random_image_size_tensor.ndim

3

In [22]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

#Zeros and ones

In [23]:
zeros = torch.zeros(size = (3,6))
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [24]:
ones = torch.ones(size=(2,5))

In [25]:
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [27]:
zeros.dtype

torch.float32

In [28]:
tensor.dtype

torch.int64

In [29]:
zeros_3 = torch.zeros(size = (2,3,3))
zeros_3

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [30]:
#creating a range of tensrs and tensos-like

In [31]:
# torch.range(1,10)
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
one_to_100 = torch.arange(start=0,end=100,step=6)
one_to_100

tensor([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [33]:
#creating tensors like

In [34]:
ten_zeros = torch.zeros_like(input=one_to_100)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
float_32_tensor = torch.tensor([1.,2.,3.], dtype=None, device='cpu', requires_grad=False)

In [36]:
float_32_tensor.dtype

torch.float32

In [37]:
# float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [38]:
multiply = float_32_tensor * float_16_tensor
multiply

tensor([1., 4., 9.])

In [39]:
some_tensor = torch.rand(size=(3,2), dtype=torch.half)
# torch.randint(low=0, high=100, size=(3,6), dtype=torch.long)
some_tensor

tensor([[0.2275, 0.7290],
        [0.5005, 0.0381],
        [0.0503, 0.9561]], dtype=torch.float16)

In [40]:
print(f"Datatype of created tensor: {some_tensor.dtype}")
print(f"Shape of created tensor: {some_tensor.shape}")
print(f"Device on which tensor is created: {some_tensor.device}")

Datatype of created tensor: torch.float16
Shape of created tensor: torch.Size([3, 2])
Device on which tensor is created: cpu


In [41]:
tens = torch.tensor([4,6,8])
tens

tensor([4, 6, 8])

In [42]:
tens+10

tensor([14, 16, 18])

In [43]:
tens*10

tensor([40, 60, 80])

In [44]:
tens-10

tensor([-6, -4, -2])

In [45]:
torch.mul(tens,10)

tensor([40, 60, 80])

In [46]:
torch.add(tens,90)

tensor([94, 96, 98])

In [47]:
torch.sub(tens,4)

tensor([0, 2, 4])

In [48]:
tens/10

tensor([0.4000, 0.6000, 0.8000])

In [49]:
# Matrix Multiplication

In [50]:
tens

tensor([4, 6, 8])

In [51]:
tensor1 = torch.tensor([[3,4,5,9], [9,8,7,4], [4,5,8,9]])
tensor2 = torch.tensor([[4,5,0],[6,7,9],[8,9,8],[9,5,2]])

print(tensor1.shape)
print(tensor2.shape)


torch.Size([3, 4])
torch.Size([4, 3])


In [52]:
%%time
torch.matmul(tensor1, tensor2)

CPU times: user 602 µs, sys: 938 µs, total: 1.54 ms
Wall time: 10.3 ms


tensor([[157, 133,  94],
        [176, 184, 136],
        [191, 172, 127]])

In [53]:
# %%time
# value = 0
# for i in range(len(tens)):
#   for j in range(len(tens[i])):
#     value += tens[i][j] * tens[i][j]
# value

In [54]:
# @ can be used in place of matmul.
torch.rand(2,120) @ torch.rand(120,2)

tensor([[28.1104, 28.9661],
        [31.5450, 31.8529]])

In [55]:
tensor1 @ tensor2

tensor([[157, 133,  94],
        [176, 184, 136],
        [191, 172, 127]])

In [56]:
tensor1 @ tensor1.T

tensor([[131, 130, 153],
        [130, 210, 168],
        [153, 168, 186]])

In [57]:
# min, max, mean, sum

In [58]:
print(torch.min(tensor1))
print(tensor1.min())

tensor(3)
tensor(3)


In [59]:
print(torch.max(tensor1))
print(tensor1.max())

tensor(9)
tensor(9)


In [60]:
print(torch.mean(tensor1.type(torch.float16)))
print(tensor1.type(torch.half).mean())

tensor(6.2500, dtype=torch.float16)
tensor(6.2500, dtype=torch.float16)


In [61]:
print(torch.sum(tensor1))
print(tensor1.sum())

tensor(75)
tensor(75)


In [62]:
print(tensor1)
print(tensor1.shape)
tensor1_reshaped = tensor1.reshape(12,1)
print(tensor1_reshaped)
tensor1_squeezed = tensor1_reshaped.squeeze()
print(tensor1_squeezed)
print(tensor1_squeezed.shape)
min_ind = tensor1_squeezed.argmin()
print(tensor1_squeezed[min_ind])
max_ind = tensor1_squeezed.argmax()
print(tensor1_squeezed[max_ind])

tensor([[3, 4, 5, 9],
        [9, 8, 7, 4],
        [4, 5, 8, 9]])
torch.Size([3, 4])
tensor([[3],
        [4],
        [5],
        [9],
        [9],
        [8],
        [7],
        [4],
        [4],
        [5],
        [8],
        [9]])
tensor([3, 4, 5, 9, 9, 8, 7, 4, 4, 5, 8, 9])
torch.Size([12])
tensor(3)
tensor(9)


In [63]:
tensor_view = tensor1.view((4,3))
tensor_view

tensor([[3, 4, 5],
        [9, 9, 8],
        [7, 4, 4],
        [5, 8, 9]])

In [64]:
tensor_view[0][0] = 10
tensor1

tensor([[10,  4,  5,  9],
        [ 9,  8,  7,  4],
        [ 4,  5,  8,  9]])

In [65]:
tensor_view

tensor([[10,  4,  5],
        [ 9,  9,  8],
        [ 7,  4,  4],
        [ 5,  8,  9]])

In [66]:
tensor1_squeezed

tensor([10,  4,  5,  9,  9,  8,  7,  4,  4,  5,  8,  9])

In [67]:
tensor1_squeezed.unsqueeze(dim=1)

tensor([[10],
        [ 4],
        [ 5],
        [ 9],
        [ 9],
        [ 8],
        [ 7],
        [ 4],
        [ 4],
        [ 5],
        [ 8],
        [ 9]])

In [68]:
tensor1_squeezed.reshape((3,2,2))

tensor([[[10,  4],
         [ 5,  9]],

        [[ 9,  8],
         [ 7,  4]],

        [[ 4,  5],
         [ 8,  9]]])

In [69]:
squeezed_zeros = torch.zeros([2,3,1,2,1])
squeezed_zeros

tensor([[[[[0.],
           [0.]]],


         [[[0.],
           [0.]]],


         [[[0.],
           [0.]]]],



        [[[[0.],
           [0.]]],


         [[[0.],
           [0.]]],


         [[[0.],
           [0.]]]]])

In [70]:
squeezed_zeros = squeezed_zeros.squeeze(1)
squeezed_zeros

tensor([[[[[0.],
           [0.]]],


         [[[0.],
           [0.]]],


         [[[0.],
           [0.]]]],



        [[[[0.],
           [0.]]],


         [[[0.],
           [0.]]],


         [[[0.],
           [0.]]]]])

In [71]:
squeezed_zeros = squeezed_zeros.unsqueeze(dim=3)
squeezed_zeros

tensor([[[[[[0.],
            [0.]]]],



         [[[[0.],
            [0.]]]],



         [[[[0.],
            [0.]]]]],




        [[[[[0.],
            [0.]]]],



         [[[[0.],
            [0.]]]],



         [[[[0.],
            [0.]]]]]])

In [72]:
permute_tensor = torch.rand(4,5,3)
print(permute_tensor)
print(permute_tensor[0][1][2])
# permute_tensor
permuted_tensor = torch.permute(permute_tensor, (1,2,0))

print(permuted_tensor[0][1][2])
permuted_tensor[0][1][2] = 1
print(permuted_tensor)
print(permute_tensor)
# permuted_tensor

tensor([[[0.7756, 0.5089, 0.8214],
         [0.2697, 0.2648, 0.1995],
         [0.3081, 0.0723, 0.8025],
         [0.0960, 0.5346, 0.3262],
         [0.2391, 0.6190, 0.0180]],

        [[0.2820, 0.9564, 0.8037],
         [0.1854, 0.8871, 0.7552],
         [0.7907, 0.5047, 0.9013],
         [0.7124, 0.5115, 0.9398],
         [0.6575, 0.5606, 0.6120]],

        [[0.3175, 0.1994, 0.1878],
         [0.8217, 0.1662, 0.3420],
         [0.0646, 0.8273, 0.4285],
         [0.9677, 0.5806, 0.0502],
         [0.4412, 0.9067, 0.1170]],

        [[0.2412, 0.5203, 0.8135],
         [0.2771, 0.0888, 0.6570],
         [0.7720, 0.0883, 0.6201],
         [0.8199, 0.2653, 0.3026],
         [0.7951, 0.7255, 0.9282]]])
tensor(0.1995)
tensor(0.1994)
tensor([[[0.7756, 0.2820, 0.3175, 0.2412],
         [0.5089, 0.9564, 1.0000, 0.5203],
         [0.8214, 0.8037, 0.1878, 0.8135]],

        [[0.2697, 0.1854, 0.8217, 0.2771],
         [0.2648, 0.8871, 0.1662, 0.0888],
         [0.1995, 0.7552, 0.3420, 0.6570]],



In [73]:
np_arr = np.arange(1.0,10.0)
np_arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [76]:
torch_tensor = torch.from_numpy(np_arr).type(torch.float32)
print(torch_tensor)
print(torch_tensor.dtype)

torch.float32


In [79]:
tor_ten = torch.ones(9)
tor_ten

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [80]:
num_arr = tor_ten.numpy()
num_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [93]:
RANDOM_SEED = 42

In [94]:
torch.manual_seed(RANDOM_SEED)
rand_tens1 = torch.rand(3,4)
rand_tens1

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [95]:
torch.manual_seed(RANDOM_SEED)
rand_tens2 = torch.rand(3,4)
rand_tens2

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [96]:
rand_tens1==rand_tens2

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [2]:
import torch
import numpy as np

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [4]:
torch.cuda.device_count()

1

In [5]:
torch_tensor = torch.tensor([1,2,3])
torch_tensor

tensor([1, 2, 3])

In [6]:
tensor_gpu = torch_tensor.to(device)
tensor_gpu

tensor([1, 2, 3], device='cuda:0')

In [9]:
tensor_cpu = tensor_gpu.cpu().numpy()
tensor_cpu

array([1, 2, 3])