<a href="https://colab.research.google.com/github/Manuj99/pytorch/blob/pytorch_1/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.8.0+cu126


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [5]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [6]:
scaler.ndim

0

In [7]:
scaler.item()

7

In [8]:
vector = torch.tensor([1,4])
vector

tensor([1, 4])

In [9]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [14]:
matrix = torch.tensor([[1,4], [2,5]])
matrix

tensor([[1, 4],
        [2, 5]])

In [16]:
matrix.ndim

2

In [17]:
matrix.shape

torch.Size([2, 2])

In [18]:
matrix[1]

tensor([2, 5])

In [23]:
tensor = torch.tensor([[[1,2,3],[4,5,6]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [24]:
tensor.ndim

3

In [25]:
tensor.shape

torch.Size([1, 2, 3])

In [30]:
tensor[0][1][2].item()

6

In [34]:
# Creating Random Tensors of size (3, 4)
random_tensor = torch.rand(3,3,5)
random_tensor


tensor([[[0.5084, 0.4800, 0.2152, 0.5863, 0.8041],
         [0.9046, 0.3503, 0.3122, 0.5366, 0.1114],
         [0.8962, 0.2940, 0.3575, 0.6200, 0.2991]],

        [[0.1226, 0.2942, 0.2460, 0.5779, 0.7898],
         [0.9926, 0.1843, 0.2015, 0.0210, 0.0137],
         [0.2788, 0.9071, 0.3618, 0.3010, 0.8520]],

        [[0.6162, 0.2346, 0.8859, 0.1707, 0.8437],
         [0.7018, 0.9820, 0.4659, 0.1915, 0.0339],
         [0.5476, 0.7924, 0.3471, 0.1283, 0.4692]]])

In [35]:
random_image_size_tensor = torch.rand(3,224,224)

In [36]:
random_image_size_tensor

tensor([[[0.7632, 0.0259, 0.4321,  ..., 0.2985, 0.6083, 0.4574],
         [0.0638, 0.9295, 0.8079,  ..., 0.7579, 0.1516, 0.4009],
         [0.6982, 0.2549, 0.6396,  ..., 0.2154, 0.5374, 0.6070],
         ...,
         [0.6873, 0.4811, 0.9958,  ..., 0.2192, 0.7870, 0.3003],
         [0.0450, 0.4612, 0.4448,  ..., 0.3661, 0.7236, 0.8281],
         [0.1688, 0.1219, 0.8697,  ..., 0.3438, 0.2288, 0.1710]],

        [[0.3397, 0.6493, 0.6649,  ..., 0.1367, 0.2960, 0.7163],
         [0.9967, 0.0508, 0.3163,  ..., 0.5168, 0.4954, 0.7816],
         [0.2688, 0.6893, 0.8816,  ..., 0.7435, 0.8773, 0.0165],
         ...,
         [0.6624, 0.4557, 0.2108,  ..., 0.6203, 0.4806, 0.6284],
         [0.8059, 0.6363, 0.2961,  ..., 0.8052, 0.9442, 0.0948],
         [0.7730, 0.3907, 0.2266,  ..., 0.3835, 0.4658, 0.5188]],

        [[0.0379, 0.0723, 0.6469,  ..., 0.7681, 0.5329, 0.8299],
         [0.1156, 0.5203, 0.3652,  ..., 0.6857, 0.8276, 0.6184],
         [0.4751, 0.8196, 0.9690,  ..., 0.5409, 0.7268, 0.

In [37]:
random_image_size_tensor.ndim

3

In [38]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

#Zeros and ones

In [52]:
zeros = torch.zeros(size = (3,6))
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [45]:
ones = torch.ones(size=(2,5))

In [46]:
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [48]:
ones.dtype

torch.float32

In [50]:
zeros.dtype

torch.float32

In [51]:
tensor.dtype

torch.int64

In [54]:
zeros_3 = torch.zeros(size = (2,3,3))
zeros_3

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [55]:
#creating a range of tensrs and tensos-like

In [58]:
# torch.range(1,10)
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
one_to_100 = torch.arange(start=0,end=100,step=6)
one_to_100

tensor([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96])

In [67]:
#creating tensors like

In [69]:
ten_zeros = torch.zeros_like(input=one_to_100)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([1,2,3], dtype=None, device='cpu', requires_grad=false)